spring:
  application:
    name: jpa
  jpa:
    show-sql: true
    properties:
      format_sql: true
      dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
  datasource:
    url: ${URL}
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: kernel360_5
    password: ${PASSWORD}
  output:
    ansi:
      enabled: always
